version: '3'

services:
  api:
    container_name: nocellos_api
    build: apps/api
    env_file:
      - .env
    restart: always
    ports:
      - ${PORT}:${PORT}
    command: uvicorn main:app --host 0.0.0.0 --port ${PORT}
  db:
    image: postgres:14.0-alpine
    container_name: nocellos_dev_db
    environment:
      - POSTGRES_PASSWORD=dev_pass
    restart: always
    ports:
      - 5431:5432 # To avoid clashing with local postgres runtime
